### ISSUE TITLE
Does the script start a new match?

### ISSUE THREAD

**Issue by emontes22** [3Tamao3/DBD-AFK-LEGION-FARMING#2]
Hello! In the description you said that you were able to farm 9k Shards in two days did you have to start the matches manually? Or after a match has ended is the script able to start a new one?

**Comment by 3Tamao3** [comment]
Hi! The script does sverything for you. Just select the Legion and press F8 and it should do everything alone.

**Comment by emontes22** [comment]
Thank you!

**Comment by 3Tamao3** [comment]
Hi! I started with the 7-Day-Experiment today. 

https://docs.google.com/spreadsheets/d/1DmQG6aEy59FFuXPX0zjsc3zuepT39HPaYvSepahDGbY/edit#gid=0
